export interface Env {
	KV: KVNamespace;
	MCP_AUTH_TOKEN: string;
	REDDIT_CLIENT_ID: string;
	REDDIT_CLIENT_SECRET: string;
	TWITTERAPI_IO_KEY: string;
	FIRECRAWL_API_KEY: string;
	YOUTUBE_API_KEY: string;
	SUPADATA_API_KEY: string;
	EXA_API_KEY: string;
	BRAVE_API_KEY: string;
	REDDIT_USER_AGENT: string;
	X_DAILY_CALL_LIMIT: string;
	FIRECRAWL_DAILY_CALL_LIMIT: string;
	YOUTUBE_SEARCH_DAILY_LIMIT: string;
	SUPADATA_DAILY_LIMIT: string;
	EXA_DAILY_CALL_LIMIT: string;
	BRAVE_DAILY_CALL_LIMIT: string;
}
